/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho;

import Classes.Departamento;
import Classes.SimpleTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author Joao
 */
public class FormDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form FormDepartamento
     */
    public FormDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        beneficio_excluir = new javax.swing.JButton();
        beneficio_editar = new javax.swing.JButton();
        beneficio_salvar = new javax.swing.JButton();
        beneficio_nome = new javax.swing.JTextField();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Departamento");

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Departamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable8);

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        beneficio_excluir.setText("Excluir");
        beneficio_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beneficio_excluirActionPerformed(evt);
            }
        });

        beneficio_editar.setText("Editar");
        beneficio_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beneficio_editarActionPerformed(evt);
            }
        });

        beneficio_salvar.setText("Salvar");
        beneficio_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beneficio_salvarActionPerformed(evt);
            }
        });

        label.setText("Departamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(beneficio_salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beneficio_editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beneficio_excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(beneficio_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(beneficio_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beneficio_salvar)
                    .addComponent(beneficio_editar)
                    .addComponent(beneficio_excluir)
                    .addComponent(jButton1))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int idEditarDepartamento = 0;
    ArrayList<Departamento> listaDepartamento = new ArrayList<Departamento>();
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        beneficio_nome.setText("");
        idEditarDepartamento = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void beneficio_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beneficio_excluirActionPerformed
        String nomeDepartamento = beneficio_nome.getText();

        if( !nomeDepartamento.equals("") ){
            Departamento departamento = new Departamento();

            try {
                departamento.deletarDepartamento( nomeDepartamento );
                atualizaTabela();
            } catch (SQLException ex) {

            }
        }
    }//GEN-LAST:event_beneficio_excluirActionPerformed

    private void beneficio_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beneficio_editarActionPerformed
        // TODO add your handling code here:
        int index = jTable8.getSelectedRow();
        TableModel model = jTable8.getModel();

        idEditarDepartamento = Integer.parseInt(model.getValueAt(index, 0).toString());
        beneficio_nome.setText( model.getValueAt(index, 1).toString() );
    }//GEN-LAST:event_beneficio_editarActionPerformed

    private void beneficio_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beneficio_salvarActionPerformed

        if( !beneficio_nome.getText().equalsIgnoreCase("") ){
            Departamento departamento = new Departamento();
            departamento.setDepartamento( beneficio_nome.getText() );
            try {
                if( idEditarDepartamento == 0 ){
                    departamento.cadastrarDepartamento();
                }else if( idEditarDepartamento > 0 ){
                    departamento.setIdDepartamento(idEditarDepartamento);
                    departamento.editarDepartamento();
                    idEditarDepartamento = 0;
                }
                beneficio_nome.setText("");
                atualizaTabela();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor insira o nome do departamento!");
        }
    }//GEN-LAST:event_beneficio_salvarActionPerformed
    
    public void atualizaTabela(){
        ArrayList<Departamento> listaDepartamento = new ArrayList<Departamento>();
        Departamento departamento = new Departamento();
        
        try {
            listaDepartamento = departamento.listarDepartamentos();
        } catch (SQLException ex) {
            Logger.getLogger(CadFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTable8 = createJtable( listaDepartamento );
        jScrollPane8.setViewportView(jTable8);
    }
    
    public JTable createJtable( ArrayList<Departamento> listaDepartamento ){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] 
        {"ID", "Departamento"};
         
         for (Departamento d:listaDepartamento){
            dados.add(new String[]
                {Integer.toString(d.getIdDepartamento()), 
                 d.getDepartamento()}
            );
         }
         
         SimpleTableModel modelo =
                 new SimpleTableModel(dados, colunas);
         
         JTable jtable = new JTable(modelo);
         return jtable;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beneficio_editar;
    private javax.swing.JButton beneficio_excluir;
    private javax.swing.JTextField beneficio_nome;
    private javax.swing.JButton beneficio_salvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable8;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
