/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho;

import Classes.Agenda;
import Classes.Cargo;
import Classes.SimpleTableModel;
import java.sql.SQLException;
import Classes.Departamento;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author Joao
 */
public class FormCargo extends javax.swing.JFrame {

    /**
     * Creates new form FormCargo
     */
    public FormCargo() {
        initComponents();
    }
    
    String idCargoEditar = "0";
    ArrayList<Cargo> listaCargo = new ArrayList<Cargo>();
    ArrayList<Departamento> listaDepartamento = new ArrayList<Departamento>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        jt_cargo = new javax.swing.JTable();
        cadastro_cargo_Limpar = new javax.swing.JButton();
        cadastro_cargo_excluir = new javax.swing.JButton();
        cadastro_cargo_Alterar = new javax.swing.JButton();
        cadastro_cargo_salvar = new javax.swing.JButton();
        cadastro_cargo_departamento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cadastro_cargo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargo");

        jt_cargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Cargo", "Departamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jt_cargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jt_cargoFocusGained(evt);
            }
        });
        jt_cargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_cargoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jt_cargoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jt_cargoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jt_cargoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jt_cargoMouseReleased(evt);
            }
        });
        jScrollPane9.setViewportView(jt_cargo);

        cadastro_cargo_Limpar.setText("Limpar");
        cadastro_cargo_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_cargo_LimparActionPerformed(evt);
            }
        });

        cadastro_cargo_excluir.setText("Excluir");
        cadastro_cargo_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_cargo_excluirActionPerformed(evt);
            }
        });

        cadastro_cargo_Alterar.setText("Alterar");
        cadastro_cargo_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_cargo_AlterarActionPerformed(evt);
            }
        });

        cadastro_cargo_salvar.setText("Salvar");
        cadastro_cargo_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_cargo_salvarActionPerformed(evt);
            }
        });

        cadastro_cargo_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_cargo_departamentoActionPerformed(evt);
            }
        });

        jLabel3.setText("Departamento:");

        jLabel2.setText("Cargo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(cadastro_cargo_salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastro_cargo_Alterar)
                .addGap(14, 14, 14)
                .addComponent(cadastro_cargo_excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastro_cargo_Limpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastro_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastro_cargo_departamento, 0, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cadastro_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cadastro_cargo_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastro_cargo_excluir)
                    .addComponent(cadastro_cargo_Alterar)
                    .addComponent(cadastro_cargo_salvar)
                    .addComponent(cadastro_cargo_Limpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_cargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt_cargoFocusGained
        if(jt_cargo.getSelectedRow() != -1){
            JOptionPane.showMessageDialog(null,"DEU BOM "+jt_cargo.getSelectedRow());
        }
    }//GEN-LAST:event_jt_cargoFocusGained

    private void jt_cargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cargoMouseClicked
        if(jt_cargo.getSelectedRow() != -1){
            JOptionPane.showMessageDialog(null,"DEU BOM "+jt_cargo.getSelectedRow());
        }
    }//GEN-LAST:event_jt_cargoMouseClicked

    private void jt_cargoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cargoMouseEntered
        if(jt_cargo.getSelectedRow() != -1){
            JOptionPane.showMessageDialog(null,"DEU BOM "+jt_cargo.getSelectedRow());
        }
    }//GEN-LAST:event_jt_cargoMouseEntered

    private void jt_cargoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cargoMouseExited
        if(jt_cargo.getSelectedRow() != -1){
            JOptionPane.showMessageDialog(null,"DEU BOM "+jt_cargo.getSelectedRow());
        }
    }//GEN-LAST:event_jt_cargoMouseExited

    private void jt_cargoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cargoMousePressed
        if(jt_cargo.getSelectedRow() != -1){
            JOptionPane.showMessageDialog(null,"DEU BOM "+jt_cargo.getSelectedRow());
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jt_cargoMousePressed

    private void jt_cargoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cargoMouseReleased
        if(jt_cargo.getSelectedRow() != -1){
            JOptionPane.showMessageDialog(null,"DEU BOM "+jt_cargo.getSelectedRow());
        }
    }//GEN-LAST:event_jt_cargoMouseReleased

    private void cadastro_cargo_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_cargo_LimparActionPerformed
        cadastro_cargo.setText("");
        cadastro_cargo_departamento.setSelectedIndex(0);

    }//GEN-LAST:event_cadastro_cargo_LimparActionPerformed

    private void cadastro_cargo_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_cargo_excluirActionPerformed
        Object[] options = {"   Sim   ", "   Não   "};
        int n = JOptionPane.showOptionDialog(null," Deseja realmente Excluir?","Sair do Programa",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[1]);
        if(n == 0){
            Integer idx = 0;
            String id_cargo = "0";

            Cargo cargo = new Cargo();

            idx = jt_cargo.getSelectedRow();
            if( idx == -1){
                JOptionPane.showMessageDialog(null, " Selecionar um item! ");
            }else{
                id_cargo =  (String) jt_cargo.getModel().getValueAt(idx, 0);

                cargo.setIdCargo( Integer.parseInt(id_cargo) );
                try {
                    cargo.deletarCargo();
                    atualizaTabelaCargo();
                } catch (SQLException ex) {
                    Logger.getLogger(CadFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_cadastro_cargo_excluirActionPerformed

    private void cadastro_cargo_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_cargo_AlterarActionPerformed
        Integer idx = 0;

        idx = jt_cargo.getSelectedRow();
        if( idx == -1){
            JOptionPane.showMessageDialog(null, " Selecionar um item! ");
        }else{
            idCargoEditar =  (String) jt_cargo.getModel().getValueAt(idx, 0);
            cadastro_cargo.setText((String) jt_cargo.getModel().getValueAt(idx, 1));
            cadastro_cargo_departamento.setSelectedItem((String) jt_cargo.getModel().getValueAt(idx, 2));
        }

    }//GEN-LAST:event_cadastro_cargo_AlterarActionPerformed

    private void cadastro_cargo_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_cargo_salvarActionPerformed
        Cargo cargo = new Cargo();
        Departamento departamento = new Departamento();

        if( !cadastro_cargo.getText().equalsIgnoreCase("") ){

            String cargotext          = cadastro_cargo.getText();
            String departamento_text  = (String)cadastro_cargo_departamento.getSelectedItem();
            int departamento_id       = 0;

            try {
                listaDepartamento = departamento.listarDepartamentos();

                for (int i = 0; i < listaDepartamento.size(); i++) {
                    if( listaDepartamento.get(i).getDepartamento().equalsIgnoreCase( departamento_text ) ){
                        departamento_id = listaDepartamento.get(i).getIdDepartamento();
                    }
                }

                cargo.setCargo(cargotext);
                cargo.setDepartamento(departamento_id);

                if(idCargoEditar == "0"){
                    cargo.cadastrarCargo();
                }else{
                    cargo.setIdCargo(Integer.parseInt(idCargoEditar));
                    cargo.EditarCargo();
                    idCargoEditar = "0";
                }
                cadastro_cargo.setText("");
                atualizaTabelaCargo();
            } catch (SQLException ex) {
                Logger.getLogger(CadFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(null, "Digite um cargo!");
        }
    }//GEN-LAST:event_cadastro_cargo_salvarActionPerformed

    private void cadastro_cargo_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_cargo_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastro_cargo_departamentoActionPerformed

    public void atualizaTabelaCargo(){
        Cargo cargo = new Cargo();
        
        try {
            listaCargo = cargo.listarCargos();
            
            jt_cargo = createJtableCargo( listaCargo );
            jScrollPane9.setViewportView(jt_cargo);
            
        } catch (SQLException ex) {
            Logger.getLogger(CadFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public JTable createJtableCargo( ArrayList<Cargo> listaCargo ){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] 
        { "ID", "Cargo","Departamento"};
         
         for (Cargo d:listaCargo){
            dados.add(new String[]
                { d.getIdCargo()+"", d.getCargo(), d.getDepartamentoString()}
            );
         }
         
         SimpleTableModel modelo =
                new SimpleTableModel(dados, colunas);
         
         JTable jtable = new JTable((TableModel) modelo);
         return jtable;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cadastro_cargo;
    private javax.swing.JButton cadastro_cargo_Alterar;
    private javax.swing.JButton cadastro_cargo_Limpar;
    private javax.swing.JComboBox<String> cadastro_cargo_departamento;
    private javax.swing.JButton cadastro_cargo_excluir;
    private javax.swing.JButton cadastro_cargo_salvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jt_cargo;
    // End of variables declaration//GEN-END:variables
}
